- name: upload rpki-data.j2
  copy:
    src=rpki-data.j2
    dest=/etc/bird/rpki-data.j2
    owner=root

- name: upload reload_rtrsub
  copy:
    src=reload_rtrsub
    dest=/usr/local/bin/reload_rtrsub
    owner=root
    mode=0755

- name: install pip3
  apt: name=python3-pip state=latest

- name: "Ensure rtrsub is installed"
  pip:
    name="rtrsub"
    state=latest
    executable=pip3

- apt:
    name=moreutils
    state=installed

- cron:
    name=rtrsub_ipv4
    hour=04
    minute={{ 59 |random(seed=inventory_hostname) }}
    state=present
    job="chronic /usr/local/bin/reload_rtrsub ipv4"
 
- cron:
    name=rtrsub_ipv6
    hour=04
    minute={{ 59 |random(seed=inventory_hostname) }}
    state=present
    job="chronic /usr/local/bin/reload_rtrsub ipv6"

- command: "{{ item }}"
  with_items:
    - "rtrsub -c https://rpki.meerval.net/api/export.json --afi ipv4 -t /etc/bird/rpki-data.j2 -o /etc/bird/rpki-data.ipv4.conf"
    - "rtrsub -c https://rpki.meerval.net/api/export.json --afi ipv6 -t /etc/bird/rpki-data.j2 -o /etc/bird/rpki-data.ipv6.conf"
